### ISSUE TITLE
Consider configuration flag to not @link to other classes

### ISSUE THREAD

**Issue by JonathanGiles** [jtulach/codesnippet4javadoc#17]
I believe our build fails because this doclet is creating Javadoc `@link` tags to link to other source files, and in some cases these other classes might not be on the classpath when the JavaDoc is generated. It would be useful to consider introducing some configuration flag to not do any linking in code snippets to other class files.

I can provide additional context in a follow-up comment, but I wanted to surface this to get initial impressions.

**Comment by jtulach** [comment]
Yes, the doclet tries to search for existing `import` statements and then seek for Java files in their packages. When an identifier in the code snippet matches existing file, it is wrapped with `@link`. This is not 100% bullet proof behavior. Sometimes the link goes to a different file, sometimes it is incorrect. However when the link isn't correct it is supposed to be rendered as plain`<code>ClassName</code>` - I have never seen build error caused by that.

For a long time I wanted to ask `javac` itself to resolve the classes. With the new JDK9+ API it might actually be relatively easy. Then the resolution should be accurate. Moreover we could also resolve methods in the code samples and turn them into links. I would find it useful myself as my snippets show code invocations most of the time.

If you want to add a new flag to disable `@link` altogether, I am ready to accept your PR. It is going to be few `if` statements somewhere and a test file. However I'd be curious to know why the problem happens in your case and not in mine.

**Comment by JonathanGiles** [comment]
@g2vinay will be owning this going forward. He has all of the context which he will share, and will then create a PR to enable this flag.

**Comment by srnagar** [comment]
The issue is not with the linking itself. `@link` works correctly (in our repo) for all the types but we have a scenario where the classes used in snippets are from `test` scoped maven dependencies which cannot be found by `@link`, rightly so. This results in a warning being logged - `Tag @
link: reference not found: <classname>`.

In our maven configuration, we have enabled `failOnWarning` for javadocs plugin which causes the build to fail and we want to keep it that way. So, when the linking fails, we want to suppress this warning.

In order to make this possible, I have created a PR to add a new flag that lets users suppress this warning when the linking fails.

PR https://github.com/jtulach/codesnippet4javadoc/pull/18

**Comment by g2vinay** [comment]
@srnagar is driving this and has submitted a PR #18  to fix this.

**Comment by srnagar** [comment]
@jtulach Thanks for merging the PR. Could you please let us know when you plan to publish a release version to Maven Central?

**Comment by srnagar** [comment]
@jtulach Just circling back to see if you have a timeline around when this change will be published to Maven.

**Comment by JonathanGiles** [comment]
@jtulach Do you have an idea on when you may do a release? We may need to temporarily fork this so that we can get a version available for our release process, but we would prefer to not do this. Thanks!

**Comment by jtulach** [comment]
I've just uploaded version 0.32 to the [staging area](
https://maven.java.net/content/repositories/orgapidesign-1085/). Give it
some testing and if it is OK, I can release it to Maven central.

st 20. 11. 2019 v 22:16 odesílatel Jonathan Giles <notifications@github.com>
napsal:

**Comment by srnagar** [comment]
@jtulach Thanks for uploading version 0.32. I verified this version in our application and everything is working as expected and can be released to Maven central!

Please let us know when it's available in Maven. Thank you once again :)

**Comment by jtulach** [comment]
OK. Let's publish the bits:
https://repo1.maven.org/maven2/org/apidesign/javadoc/codesnippet-doclet/0.32/
