### ISSUE TITLE
Add support for JEP 413 - code snippets in Java API Documentation

### ISSUE THREAD

**Issue by JonathanGiles** [jtulach/codesnippet4javadoc#27]
It would be great to be able to transition away from the codesnippets4javadoc library over time as the [JEP 413 support](https://openjdk.java.net/jeps/413) finds its way into JDK 18 (hopefully). If the codesnippets4javadoc library could support the existing and new javadoc syntax, we could then transition our snippets to the new syntax and only include the codesnippets4javadoc library conditionally on builds where the JDK version is less than 18.

Adding this as a feature request, but I may look into implementing this at some point in the future.

**Comment by jtulach** [comment]
Yes, support for JEP-413 would be great! Having such form of _forward compatibility_ would be amazing. One could write the docs in a fully portable way, use this plugin on pre-JDK18 JDKs and on newer JDKs disable `codesnippet4javadoc` and rely on standard `javadoc`. That way the goal of `codesnippet4javadoc` would be fully fulfilled. We would deliver the future of Java right now on any JDK8+.

Rather than enabling/disabling some syntax conditionally I'd suggest to add an explicit options:
* support current snippet format? on/off
* support JEP413 snippet format? on/off

Current projects would run with the first option on. Possibly also enabling the other option and later disabling the first (legacy) one as soon as all snippets become JEP-413 compliant. Ultimately, after switching to JDK18+ those projects could stop using `codesnippet4javadoc` altogether.

**Comment by jtulach** [comment]
Initial steps taken in #27.

**Comment by jtulach** [comment]
Version [0.80 with JEP-413](https://repo1.maven.org/maven2/org/apidesign/javadoc/codesnippet-doclet/0.80/) support has been uploaded to Maven central. There is a [jep413 testing project](https://github.com/jtulach/codesnippet4javadoc/tree/master/jep413/src) that verifies the support for `@snippet` & co. is good enough and compatible with behavior of **JDK18**. We have the initial support and we can make it better.
